name: "setup-ghcli"
description: "Install a specific version of GitHub cli and add it to the PATH"
author: "twildber"
inputs:
  version:
    description: "The version to use. Example: 2.28.0"
    default: "latest"
    required: false
outputs:
  gh_version:
    description: "The installed version"
runs:
  using: "node16"
  main: "lib/index.js"
