name: build & test

on:
  pull_request:
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Run test on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm ci
      
      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build

      - name: Test installing gh cli
        id: install
        uses: ./
        with:
          version: 2.28.0
      
      - name: Test gh command works on ubuntu
        if: matrix.os == 'ubuntu-latest'
        env:
          INSTALL_OUTPUT: ${{ steps.install.outputs.gh_version }}
        run: |
          echo "Installed gh version: $INSTALL_OUTPUT"
          $RUNNER_TOOL_CACHE/gh/2.28.0/x64/bin/gh --version

      - name: Test gh command works on macos
        if: matrix.os  == 'macos-latest'
        env:
          INSTALL_OUTPUT: ${{ steps.install.outputs.gh_version }}
        run: |
          echo "Installed gh version: $INSTALL_OUTPUT"
          ls $RUNNER_TOOL_CACHE/gh/2.28.0/x64
          ls $RUNNER_TOOL_CACHE/gh/2.28.0/x64.complete
            
      - name: Test gh command works on windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        env:
          INSTALL_OUTPUT: ${{ steps.install.outputs.gh_version }}
        run: |
          echo "Installed gh version: %INSTALL_OUTPUT%"
          %RUNNER_TOOL_CACHE%\gh\2.28.0\x64\bin\gh --version